# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGIS_Vplugin
                                 A QGIS plugin
 QGIS에서 브이월드를 쉽게 활용할 수 있도록 기능제공
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-22
        copyright            : (C) 2024 by spaceN.or.kr
        email                : dy.lee@spacen.or.kr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


import os
import sys

# 번들된 의존성(openpyxl, xlrd, et_xmlfile) 경로 등록
_LIBS_DIR = os.path.join(os.path.dirname(__file__), 'libs')
if os.path.isdir(_LIBS_DIR) and _LIBS_DIR not in sys.path:
    sys.path.insert(0, _LIBS_DIR)


def classFactory(iface):
    from .v_world import VWorld
    return VWorld(iface)